[discovery]
minCopies = 1

[joint]
formatFields = [
    { name = "DP" },
    { name = "GQ" },
    { name = "AD" },
    { name = "PL" },
    { name = "OL" }
]

[joint.gt]
overlapMode = "MISSING"

[joint.gt.revision]
enable = true
minAssumedAlleleFrequency = 0.0001
snvPriorCalibration = 0.6
indelPriorCalibration = 0.45
