[discovery]
minCopies = 1

[joint]
formatFields = [
    { name = "DP" },
    { name = "GQ" },
    { name = "AD" },
    { name = "PL" },
    { name = "OL" }
]

[joint.gt.revision]
enable = true
minAssumedAlleleFrequency = 0.0001
