[variantDiscovery]
minCopies = 1

[joint]
formatFields = [
    { name = "DP" },
    { name = "GQ" },
    { name = "AD" },
    { name = "PL" },
    { name = "OL" }
]

[joint.gt]
overlapMode = "MISSING"
