[spark]
# Snappy compression of intermediate data during sort/join passes
# Usually only one of compressTempRecords and compressTempFiles should be true.
# compressTempRecords: when individual input records are large s.t. they individually compress well
compressTempRecords = false
# compressTempFiles: otherwise
compressTempFiles = true

[discovery]
allowDuplicateSamples = false
minCopies = 0
minAQ1 = 0
minAQ2 = 0

[joint]
keepTrailingFields = false
