[spark]
# Snappy compression of intermediate data during sort/join passes
# Usually only one of compressTempRecords and compressTempFiles should be true.
# compressTempRecords: when individual input records are large s.t. they individually compress well
compressTempRecords = false
# compressTempFiles: otherwise
compressTempFiles = true

[discovery]
allowDuplicateSamples = false
minCopies = 0

[joint]
# Genome range bin size used for joins; tunes perf with data-dependent goldilocks value
binSize = 16
