name: build
on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: ktlint
      run: mvn antrun:run@ktlint
    - name: ktlint-format
      run: mvn antrun:run@ktlint-format

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - name: deps
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y bcftools tabix
        curl -LSs https://archive.apache.org/dist/spark/spark-3.2.2/spark-3.2.2-bin-hadoop3.2.tgz | tar zx
        SPARK_HOME=$(find $(pwd) -type d -name "spark-*")
        echo "SPARK_HOME=$SPARK_HOME" >> $GITHUB_ENV
        git status
    - name: unit tests
      run: mvn test
    - name: build
      run: mvn package -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=warn
    - name: test 5%
      run: DV1KGP_5PCT=1 prove -v test/dv1KGP.t
    - name: test 100%
      run: prove -v test/dv1KGP.t
    - name: upload jar
      uses: actions/upload-artifact@v4
      with:
        name: GLnext-jar
        path: target/GLnext-*.jar
