name: build
on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: ktlint
      run: mvn antrun:run@ktlint
    - name: ktlint-format
      run: mvn antrun:run@ktlint-format

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: spark
      run: |
        curl -LSs https://dlcdn.apache.org/spark/spark-3.1.3/spark-3.1.3-bin-hadoop3.2.tgz | tar zx
        SPARK_HOME=$(find $(pwd) -type d -name "spark-*")
        echo "SPARK_HOME=$SPARK_HOME" >> $GITHUB_ENV
    - name: build
      run: mvn package -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.shade=warn
    - name: test
      run: prove -v test/*.t
